'$schema' = "node_modules/wrangler/config-schema.json"
compatibility_date = "2024-09-23"

name = "digirati-tanc-workshops"
pages_build_output_dir = "./docs/dist"
account_id = "ae784157f30fd7164f22b075991c1caa"
